fix: Fix context parsing
juspay/superposition pull request #145
Opened 2024-07-02 11:19 UTC by mahatoankitkumar

## Problem
For number in context, it would consider it as an integer as whole, even if it was an array

## Solution
Fixed the parsing for number

2024-07-02 11:54 UTC, sauraww approved these changes

2024-07-02 11:59 UTC, ShubhranshuSanjeev requested changes

2024-07-02 11:59 UTC, ShubhranshuSanjeev commented on crates/frontend/src/utils.rs
This could be the case for other types also, like string.

2024-07-02 12:09 UTC, Datron commented on crates/frontend/src/utils.rs
> +                _ => Err("Invalid number or number array format".to_string()),
Can we also include the value that failed?

2024-07-02 12:10 UTC, Datron commented on crates/frontend/src/utils.rs
> +        ConfigValueType::Number | ConfigValueType::Integer => {
We should treat these two differently, and parse them into their corresponding types. 
Integer - i32
Number - f32

2024-07-02 12:10 UTC, Datron commented on crates/frontend/src/utils.rs
> +        ConfigValueType::Number | ConfigValueType::Integer => {
Open to opinions on this

2024-07-02 12:21 UTC, pratikmishra356 commented on crates/frontend/src/utils.rs
>          ConfigValueType::String => Ok(Value::String(val.to_string())),
array check should be for string also

2024-07-03 11:26 UTC, ShubhranshuSanjeev approved these changes

2024-07-03 11:47 UTC, pratikmishra356 approved these changes

2024-07-03 11:47 UTC, merged