[Client] Add support for `zig` client library
juspay/superposition pull request #160
Opened 2024-07-14 07:51 UTC by NishantJoshi00

### Description

Adding support for `zig` client for superposition. The steps to work with the client are mentioned in the `README.md` file in the client.

2024-07-15 06:10 UTC, Datron commented
@NishantJoshi00 can we remove the merge commit? It breaks semantic guidelines here. Please rebase if possible

2024-07-15 06:13 UTC, NishantJoshi00 commented
> @NishantJoshi00 can we remove the merge commit? It breaks semantic guidelines here. Please rebase if possible

I have done that 👍 . 
But, I am curious. What merge policy do you use?

2024-07-15 06:29 UTC, Datron commented
rebase and merge/squash and merge, depending on the use-case

2024-07-15 07:06 UTC, NishantJoshi00 commented
> squash and merge

In this case, my commit messages shouldn't matter, only the PR title would be of significance, right?

2024-07-15 10:45 UTC, Datron commented
@NishantJoshi00 yup

2024-07-21 11:46 UTC, Datron commented
@juspay/sdk-backend can we start reviewing this?

2024-07-24 10:02 UTC, Datron requested changes
@NishantJoshi00 few changes:

- We have to avoid the clone of superposition into the client
- link to the binaries in the parent folder
- binaries should be compiled for the target platform
- can you specify the min version of zig 
- can you add a zig and zls package in flake.nix
- Avoid relative paths

Let us know if we need to make any changes to make this work.

2024-07-24 13:03 UTC, NishantJoshi00 commented on clients/zig/build.zig.zon
> +    .name = "pauli",
Yes

2024-07-24 13:05 UTC, NishantJoshi00 commented on clients/zig/example/src/main.zig
> +    const setup_config = cac_client.SetupConfig{ .tenant = "public", .update_frequency = 10, .hostname = "http://localhost:8080" };
I had created and deployed superposition with public as a tenant as mentioned in the guide, will change that

2024-07-24 13:09 UTC, NishantJoshi00 commented on clients/zig/build.zig.zon
> +    //.minimum_zig_version = "0.11.0",
will add that

2024-07-24 13:11 UTC, NishantJoshi00 commented on clients/zig/src/cac.zig
> +    // cac_bindings.cac_free_string(s_ptr.ptr);
Let's translate it to rust concepts and understand this.
most of the functions imagine are returning `&String` while this function is accepting `&mut String`. Will this work in rust?

I am looking at this with a similar lens

2024-07-24 13:11 UTC, NishantJoshi00 commented on clients/zig/src/expt.zig
> +        expt_bindings.expt_start_polling_update(self.config.tenant.ptr);
Sure

2024-07-24 13:16 UTC, NishantJoshi00 commented on clients/zig/Makefile
> +	zig test -I../../headers -lc  src/cac.zig ../../target/debug/libcac_client.so
This is no longer required, I was using this initially to test it. Will remove this

2024-07-24 13:18 UTC, NishantJoshi00 commented on clients/zig/build.zig
> +            \\   git clone https://github.com/juspay/superposition.git
I think when using this client as a dependency, we need some mechanism to be able to link the library, header files. By, doing this I don't need to worry about if you have the `.so` files present in any of your `lib` paths (same goes to header files). But, it does incur the cost of compilation.

I think one possible fix might be to only build the client crates, while not touching the others.

What do you think?

2024-07-24 13:19 UTC, ShubhranshuSanjeev commented on clients/zig/build.zig.zon
> +    .name = "pauli",
Can we have a generic name `zig-cac-client`? We don't want to get into naming clients for other languages too.

2024-07-24 13:22 UTC, NishantJoshi00 commented on clients/zig/Makefile
> +	zig test -I../../headers -lc  src/cac.zig ../../target/debug/libcac_client.so
the libs and headers are figured out in build by build.zig

2024-07-24 13:23 UTC, NishantJoshi00 commented on clients/zig/build.zig.zon
> +    .name = "pauli",
sure, I started of with this, will change that

2024-07-25 10:52 UTC, NishantJoshi00 commented on clients/zig/README.md
> +-   As this client leverages `build.zig.zon` file for managing dependencies. Your zig version should atleast satisfy the minimum version mentioned in the `build.zig.zon` file.
This is part of the `example/` folder. I will add a README in that folder too

2024-07-29 06:09 UTC, Datron commented on clients/zig/build.zig
> +            \\   git clone https://github.com/juspay/superposition.git
Yeah you can only build the clients rather than the whole project

2025-02-25 06:12 UTC, closed without merging