fix: remove process, filter env variables
juspay/superposition pull request #174
Opened 2024-07-16 11:44 UTC by pratikmishra356

## Problem
First process was allowed in js_function sandbox environment
we need to enable env variables that is required for js_functions only

## Solution
Remove process from vm , delete all env variable keys except keys mentioned under `FUNCTION_ENV_VARIABLES`

## Environment variable changes
NA

## Pre-deployment activity
Add FUNCTION_ENV_VARIABLES and mention all env that is required for js_function

## Post-deployment activity
NA

## API changes
| Endpoint        | Method           | Request body  | Response Body |
| ------------- |:-------------:| -----:| ----------------:|
| API      | GET/POST, etc | request | response |

## Possible Issues in the future
NA

2024-07-17 05:37 UTC, Datron requested changes

2024-07-17 05:37 UTC, Datron commented on .env.example
> +FUNCTION_ENV_VARIABLES="SERVICE_NAME"
This should not be an ENV. Let us hard code it in file, we have too many ENVs today

2024-07-18 06:42 UTC, Datron approved these changes

2024-07-18 06:43 UTC, mahatoankitkumar approved these changes

2024-07-18 06:43 UTC, merged