feat: adddig ruby cac client
juspay/superposition pull request #186
Opened 2024-07-29 17:25 UTC by Subhash703

## Problem
Describe the problem you are trying to solve here

## Solution
Created this ruby module which provides a interface for the CAC (Configuration as Code) allowing you to interact with the CAC server to retrieve and manage configurations

## Environment variable changes

What ENVs need to be added or changed

## Pre-deployment activity
Things needed to be done before deploying this change (if any)

## Post-deployment activity
Things needed to be done after deploying this change (if any)

## API changes
| Endpoint        | Method           | Request body  | Response Body |
| ------------- |:-------------:| -----:| ----------------:|
| API      | GET/POST, etc | request | response |

## Possible Issues in the future
Describe any possible issues that could occur because of this change

2024-08-27 09:47 UTC, mahatoankitkumar commented
@Subhash703 Can you add a Readme.md here with steps to add this to a separate project and an example main file to test?

2024-08-28 01:43 UTC, mahatoankitkumar requested changes
@Subhash703 can you please extract the examples in a different file?

2024-08-28 02:10 UTC, mahatoankitkumar requested changes

2024-08-28 02:10 UTC, mahatoankitkumar commented on clients/ruby/cac-client/cacclient.rb
> +    libpath = File.expand_path(File.join(__dir__, "/../../../target/debug/libcac_client.#{extension}"))
Read library path from ENV
SUPERPOSITION_LIB_PATH

2024-08-28 02:10 UTC, mahatoankitkumar commented on clients/ruby/exp-client/expclient.rb
> +  libpath = File.expand_path(File.join(__dir__, "/../../../target/debug/libexperimentation_client.#{extension}"))
Here also

2024-08-28 19:07 UTC, Subhash703 commented on clients/ruby/cac-client/cacclient.rb
> +    libpath = File.expand_path(File.join(__dir__, "/../../../target/debug/libcac_client.#{extension}"))
Updated

2024-09-01 18:23 UTC, mahatoankitkumar requested changes

2024-09-01 18:23 UTC, mahatoankitkumar commented on clients/ruby/README.MD
> +To use functions from clients, refer to <span style="color: #808080" >main.rb </span> files in the respective clients.
Add proper steps to add documentation on how to add this to a separate project?

2024-09-04 11:07 UTC, mahatoankitkumar commented on clients/ruby/cac-client/cacclient.rb
> +    attach_function :cac_get_default_config, [ArcClient.by_ref, :string], :string
Can we improve the return type for the functions like cac_get_config, cac_get_resolved_config and others to respective types like map .....
Refer haskell client.

2025-02-25 06:13 UTC, closed without merging