ci(nix): Run Haskell clients in CI
juspay/superposition pull request #191
Opened 2024-07-31 08:18 UTC by shivaraj-bh

## Problem
See https://github.com/juspay/superposition/pull/188

## Solution
Do a runtime check on the Haskell clients in CI to avoid https://github.com/juspay/superposition/pull/188 in the future

2024-08-01 05:36 UTC, Datron approved these changes

2024-09-04 13:03 UTC, Datron requested changes
update nix ci to om ci

2024-09-04 13:31 UTC, srid commented on .github/workflows/nix.yaml
>        - run: nixci --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} build --systems "github:nix-systems/${{ matrix.system }}"
Just needs to be rebased from `main`. This PR shows outdated code due to force-pushes on `main`.

2024-09-04 14:17 UTC, shivaraj-bh commented on .github/workflows/nix.yaml
>        - run: nixci --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} build --systems "github:nix-systems/${{ matrix.system }}"
See https://github.com/juspay/superposition/pull/191/commits/764c7a7eb0666e5d74014defd4df884aba77f0fe

2024-09-05 00:24 UTC, srid approved these changes

2024-09-05 05:56 UTC, Datron approved these changes

2024-09-05 11:39 UTC, sauraww approved these changes

2024-09-05 11:40 UTC, merged