refactor: Enhance context form and display unsupported operators in o…
juspay/superposition pull request #217
Opened 2024-09-02 19:34 UTC by sauraww

…verrides UI

## Problem
Describe the problem you are trying to solve here

## Solution
Provide a brief summary of your solution so that reviewers can understand your code

## Environment variable changes

What ENVs need to be added or changed

## Pre-deployment activity
Things needed to be done before deploying this change (if any)

## Post-deployment activity
Things needed to be done after deploying this change (if any)

## API changes
| Endpoint        | Method           | Request body  | Response Body |
| ------------- |:-------------:| -----:| ----------------:|
| API      | GET/POST, etc | request | response |

## Possible Issues in the future
Describe any possible issues that could occur because of this change

2024-09-04 13:00 UTC, Datron commented
@sauraww can you update PR description and add some screenshots/videos of fixes made?

2024-09-06 08:01 UTC, Datron approved these changes

2024-09-06 09:54 UTC, Datron approved these changes

2024-09-06 10:38 UTC, ShubhranshuSanjeev requested changes

2024-09-06 10:38 UTC, ShubhranshuSanjeev commented on crates/frontend/src/pages/home.rs
>              };
```suggestion
            let op = match condition.operator.clone() {
                ConditionOperator::Is => "=",
                ConditionOperator::In => "IN",
                ConditionOperator::Has => "HAS",
                ConditionOperator::Between => "BETWEEN",
                ConditionOperator::Other(op) => op.clone()
            };
```

2024-09-06 10:38 UTC, ShubhranshuSanjeev commented on crates/frontend/src/components/context_form/utils.rs
> +        ConditionOperator::Other(op) => {
I guess, since we are clear on not supporting any unknown operator through forms, this particular variant can be dropped in future.

2024-09-06 14:21 UTC, ShubhranshuSanjeev approved these changes

2024-09-06 14:24 UTC, merged