Feat/webhook cruds
juspay/superposition pull request #313
Opened 2024-12-17 08:36 UTC by mahatoankitkumar

## Problem
Webhook Crud

## Post-deployment activity
Change the execute_webhook_call to take webhooks from the table instead of tenant_config.

2024-12-17 13:24 UTC, Datron commented on crates/context_aware_config/src/api/webhooks/handlers.rs
> +use actix_web::{
@mahatoankitkumar I don't think this should sit in CAC as its used across all crates. You should move webhooks code to superposition crate

2024-12-17 13:24 UTC, Datron commented on crates/service_utils/src/helpers.rs
> +    println!("<<>> response: {:?}", response);
Might need to remove this or use a log

2024-12-17 13:24 UTC, Datron commented on crates/service_utils/src/helpers.rs
> +    println!("<<>> {}", serde_json::to_string(&a).unwrap());
remove or make into log

2024-12-17 13:25 UTC, Datron commented on crates/superposition/Superposition.cac.toml
> +], "authorization" = { key = "juspay_token", value = "GALACTUS_API_KEY" } } }
This shouldn't be present in the open source version

2024-12-17 13:25 UTC, Datron requested changes
took a quick glance

2025-04-22 08:13 UTC, Datron requested changes
Can we remove the empty helpers.rs file?

2025-04-22 08:13 UTC, Datron commented on crates/superposition_types/src/webhook.rs
> +
Can we use derive_more::Display? You won't need this code

2025-04-22 08:13 UTC, Datron commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/down.sql
> +-- This file should undo anything in `up.sql`
Can we add some SQL for drop as well?

2025-04-22 08:13 UTC, Datron commented on crates/superposition/src/webhooks/handlers.rs
> +}
Would `?` not suffice here and then use `Ok(HttpResponse::NoContent().finish())` as the final line

2025-04-22 09:35 UTC, ayushjain17 requested changes

2025-04-22 09:35 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +}
instead of implementing this, you can directly derive `strum_macros::Display`

2025-04-22 09:35 UTC, ayushjain17 commented on crates/superposition_types/src/database/models/cac.rs
> +    pub last_modified_at: NaiveDateTime,
don't use `NaiseDateTime`, use `DateTime<Utc>` everywhere
we had to migrate all the time formats from `NaiveDateTime` to `DateTime<Utc>` due to smithy
```suggestion
    pub last_modified_at: DateTime<Utc>,
```

2025-04-22 09:35 UTC, ayushjain17 commented on crates/superposition/src/webhooks/types.rs
> +pub struct WebhookName(String);
should this not have been used in the `Webhook` model as well ?

2025-04-22 09:35 UTC, ayushjain17 commented on crates/superposition/src/webhooks/types.rs
can we please move these types to `superposition_types/src/api/webhooks.rs`

2025-04-22 09:35 UTC, ayushjain17 commented on crates/superposition/src/webhooks/helper.rs
this is an empty file, is this needed ?

2025-04-22 09:35 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
pending review

2025-04-22 09:37 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +
for enums, its better to use `strum_macros::Display`, they provide more options for modification via attributes of the macro

2025-04-22 16:00 UTC, mahatoankitkumar commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    name text PRIMARY KEY,
Already discussed earlier to have name as primary key for simpilicity

2025-04-22 16:02 UTC, mahatoankitkumar commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    method text NOT NULL DEFAULT 'POST',
Don't want to restrict it with some method
Many may not follow strict rules in their service.

2025-04-22 16:02 UTC, mahatoankitkumar commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    version text NOT NULL,
The same way
Actually didn't get you here.

2025-04-22 16:04 UTC, mahatoankitkumar commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    last_modified_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
@Datron 's adviced earlier to use without timezone, and what's the issue with default here?

2025-04-22 19:39 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
smithy model needs to be added for this

2025-04-24 06:26 UTC, Datron commented on workspace_template.sql
> +    change_reason TEXT DEFAULT '' NOT NULL;
```suggestion
    change_reason TEXT DEFAULT '' NOT NULL,
```

2025-04-24 12:39 UTC, Datron requested changes

2025-04-28 18:32 UTC, ayushjain17 requested changes

2025-04-28 18:32 UTC, ayushjain17 commented on smithy/models/webhook.smithy
tests not added

2025-04-28 18:32 UTC, ayushjain17 commented on smithy/models/webhook.smithy
ts-client changes not added

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition_types/src/database/models/cac.rs
> +pub struct Webhook {
just a question in general, should we have a separate models file for webhook or the other general models which we might add in future ?
something like either: `models/webhook.rs` or maybe `models/other.rs`

raising this, just because we already have `cac` and `experimentation` in their separate files, and models.rs files contain `superposition` schema level models, and `webhook` is not specific to `cac`

we can rather say its more specific to `experimentation` for now, but when we would want to extend it, `models/experimentation.rs` would not remain the best fit for.

thus, suggesting either of: `models/webhook.rs` or `models/other.rs`

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +}
please move these to `superposition_types/src/api/webhook.rs`

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +}
rather if all the types here are `API` types only then all of it can be moved to `superposition_types/src/api/webhook.rs`

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +    request: web::Json<CreateWebhookRequest>,
is this correct ? CreateRequest type is being used in update ?
CreateRequest already accepts `name` in it, and you are also taking `name` from path_params

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +            webhook::custom_headers.eq(req.custom_headers),
`change_reason` not being set

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +        ))
instead of manually setting all the values from request, simply derive `AsChangeset` on the `UpdateWebhookRequest` type which you are going to add, and so:
```suggestion
        .set((
            req,
            webhook::last_modified_by.eq(user.email),
            webhook::last_modified_at.eq(Utc::now()),
        ))
```

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +async fn delete_webhook(
if we are maintaining versions, should a delete `API` at all exist ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    events varchar(100)[] NOT NULL CHECK (array_position(events, NULL) IS NULL),
shouldn't the values of the events be ENUMs ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +    pub version: Option<String>,
why should create take version ?
shouldn't this be auto incremented ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +        max_retries: 0,
why are we not taking this from the user ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +        version: req.version.unwrap_or("v1".to_owned()),
shouldn't this be auto generated ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +    let events: Vec<String> = req
we can avoid writing this conversion again and again, we just need to update the type of the model correctly 
`Vec<WebhookEvent>`

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +            .get_result(&mut conn);
+1
all the error handling being done in the next few lines, will get auto handled

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +            webhook::version.eq(req.version.unwrap_or("v1".to_owned())),
ideally, this should not be a user updated value, on every update, this should get auto incremented, right ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +            webhook::url.eq(req.url),
shouldn't the user be allowed to update `max_retries` as well ?

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/webhooks.rs
why are we adding this into `superposition` crate ?
`webhook` is a core functionality, this crate is just needed to run things in a local setup

2025-04-28 18:32 UTC, ayushjain17 commented on crates/superposition/src/main.rs
is frontend change going to be a separate PR ?

2025-04-29 11:49 UTC, mahatoankitkumar commented on crates/superposition_types/src/webhook.rs
>  }
Will be removed in the subsequent PR

2025-04-29 11:52 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/handlers.rs
> +async fn delete_webhook(
Why not?

2025-04-29 11:52 UTC, mahatoankitkumar commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    events varchar(100)[] NOT NULL CHECK (array_position(events, NULL) IS NULL),
If we add more events to it in future, it would need db change, so adding the enum check in the code is more feasible

2025-04-29 11:53 UTC, mahatoankitkumar commented on crates/superposition_types/src/webhook.rs
> +    pub version: Option<String>,
Version was not kept for that reason

2025-04-29 11:53 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/handlers.rs
> +        max_retries: 0,
Not right now, as we are not supporting the retries yet

2025-04-29 11:53 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/handlers.rs
> +        version: req.version.unwrap_or("v1".to_owned()),
will explain this

2025-04-29 11:55 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/handlers.rs
> +    let events: Vec<String> = req
didn't get

2025-04-29 11:55 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/handlers.rs
> +            webhook::version.eq(req.version.unwrap_or("v1".to_owned())),
will explain

2025-04-29 11:55 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/handlers.rs
> +            webhook::url.eq(req.url),
will explain

2025-04-29 11:56 UTC, mahatoankitkumar commented on crates/superposition/src/main.rs
yes

2025-04-29 18:05 UTC, ayushjain17 requested changes

2025-04-29 18:05 UTC, ayushjain17 commented on crates/superposition_types/src/database/models/others.rs
> +        };
instead of deriving specifically `ToSql` and `FromSql`
you derive these on the type:

`strum_macros::Display, strum_macros::EnumString` 
and implement these:
```
impl TryFrom<String> for WebhookVersion {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        value
            .as_str()
            .try_into()
            .map_err(|e| format!("Invalid WebhookVersion: {e}"))
    }
}

impl From<&WebhookVersion> for String {
    fn from(value: &WebhookVersion) -> Self {
        value.to_string()
    }
}
```

then you can conditionally (behind `cgf`) derive `TextFromSql, TextToSql`

2025-04-29 18:05 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +impl ToSql<Text, Pg> for WebhookEvent {
we can do same here as well

2025-04-29 18:05 UTC, ayushjain17 commented on crates/superposition_types/src/webhook.rs
> +impl ToSql<Text, Pg> for WebhookEvent {
also, its a core type to the model, can we move this type to the `models/others.rs` file itself

2025-04-29 18:07 UTC, ayushjain17 commented on crates/superposition_types/src/api/webhook.rs
> +    pub change_reason: String,
```suggestion
    pub change_reason: ChangeReason,
```

2025-04-29 18:07 UTC, ayushjain17 commented on crates/superposition_types/src/api/webhook.rs
> +    pub description: Option<String>,
```suggestion
    pub description: Option<Description>,
```

2025-04-29 18:08 UTC, ayushjain17 commented on crates/superposition_types/src/database/models/others.rs
> +    pub description: String,
```suggestion
    pub description: Description,
```

2025-04-29 18:08 UTC, ayushjain17 commented on crates/superposition_types/src/database/models/others.rs
> +    pub change_reason: String,
```suggestion
    pub change_reason: ChangeReason,
```

2025-04-30 04:56 UTC, mahatoankitkumar commented on crates/superposition_types/src/api/webhook.rs
> +    pub version: Option<WebhookVersion>,
We decided to keep it, as we have enum for this now
later no chnage in API contract would be required.

2025-04-30 05:11 UTC, mahatoankitkumar commented on crates/superposition_types/src/database/models/others.rs
> +    pub custom_headers: Option<Value>,
Yes

2025-04-30 05:14 UTC, mahatoankitkumar commented on smithy/models/webhook.smithy
Will add test in the subsequent PR 🥺

2025-04-30 05:15 UTC, mahatoankitkumar commented on smithy/models/webhook.smithy
Added Simthy file, but its not generating ts-client

2025-04-30 05:17 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/helper.rs
> +}
No its for webhookEvent Uniqueness

2025-04-30 10:06 UTC, pratikmishra356 commented on workspace_template.sql
> +        method text NOT NULL DEFAULT 'POST',
should we have here http_method , instead of text ?

2025-04-30 10:08 UTC, pratikmishra356 commented on workspace_template.sql
> +        enabled boolean NOT NULL,
shouldn't default be false here ?

2025-04-30 10:14 UTC, pratikmishra356 commented on workspace_template.sql
> +        version text NOT NULL,
why we need version in webhook ?

2025-04-30 10:17 UTC, pratikmishra356 commented on smithy/models/webhook.smithy
> +        method: String
we should have enum for methods

2025-04-30 10:18 UTC, mahatoankitkumar commented on workspace_template.sql
> +        version text NOT NULL,
https://github.com/juspay/superposition/discussions/287#discussioncomment-11332984

2025-04-30 10:28 UTC, ayushjain17 commented on crates/superposition_types/src/database/models/others.rs
> +    pub custom_headers: Option<Value>,
should we consider this :
```suggestion
    pub custom_headers: Map<String, Value>,
```
and default value as '{}'::json ?

2025-04-30 10:31 UTC, ayushjain17 commented on crates/superposition/src/webhooks/handlers.rs
> +        version: req.version.unwrap_or(WebhookVersion::V1),
if we are planning to keep this in the request, can we use `Default` trait here, because when someone would be configuring at a later point in time, the Default value we can just make sure is always the newer value

```suggestion
        version: req.version.unwrap_or_default(),
```

2025-04-30 10:45 UTC, pratikmishra356 commented on crates/superposition_types/src/database/models/others.rs
> +    pub version: WebhookVersion,
here WebhookVersion is being typed to version which has V1 enum , 
then can you type this also in smithy

2025-04-30 10:46 UTC, pratikmishra356 commented on crates/superposition_types/src/database/models/others.rs
> +    pub version: WebhookVersion,
Also user can give any api version , why we are controlling that value from backend code

2025-04-30 10:51 UTC, mahatoankitkumar commented on crates/superposition_types/src/database/models/others.rs
> +    pub version: WebhookVersion,
Because this is the payload version, which is just V1 for now.

2025-04-30 11:08 UTC, mahatoankitkumar commented on workspace_template.sql
> +        enabled boolean NOT NULL,
Not needed, as it is required field, the user will have to provide it

2025-04-30 11:26 UTC, pratikmishra356 commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/down.sql
> +DROP TABLE IF EXISTS public.webhooks;
lets drop http_method type also here

2025-04-30 11:32 UTC, pratikmishra356 commented on crates/superposition_types/src/api/webhook.rs
> +    pub name: String,
can we make it typed like other entity name with some validation like no spaces 
and similar changes in db types

2025-04-30 11:54 UTC, pratikmishra356 commented on crates/superposition/src/webhooks/handlers.rs
> +    let webhooks = fetch_webhook(&params.into_inner(), &schema_name, &mut conn)?;
```suggestion
    let webhook_row = fetch_webhook(&params.into_inner(), &schema_name, &mut conn)?;
```

2025-04-30 11:55 UTC, ayushjain17 commented on crates/superposition_types/src/api/webhook.rs
> +    pub name: String,
this already exists
```suggestion
    pub name: WebhookName,
```

2025-04-30 12:04 UTC, pratikmishra356 commented on docker-compose/postgres/db_init.sql
> +    custom_headers json,
can we make this not null , and add empty {} by default 
as it help in not doing repeated some check in our code

2025-04-30 13:38 UTC, ayushjain17 commented on crates/superposition/src/main.rs
> +                            .wrap(OrgWorkspaceMiddlewareFactory::new(true, false))
shouldn't it be this ?
```suggestion
                            .wrap(OrgWorkspaceMiddlewareFactory::new(true, true))
```

2025-04-30 13:48 UTC, ayushjain17 approved these changes

2025-05-01 06:39 UTC, Datron approved these changes

2025-05-01 06:39 UTC, Datron commented on crates/superposition/src/webhooks/helper.rs
> +}
@mahatoankitkumar Does this prevent multiple listeners on a single event? We might need this, I won't block this PR on this but we should enable multiple listeners on a particular event. There is no reason to restrict it, and as we have seen all webhook providers like Juspay, stripe, razorpay lets you do this.

2025-05-01 06:39 UTC, Datron commented on crates/superposition_types/migrations/2024-12-06-112348_webhooks/up.sql
> +    last_modified_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
We discussed this offline and resolved it

2025-05-01 06:39 UTC, Datron commented on docker-compose/postgres/db_init.sql
> +    events varchar(100)[] NOT NULL CHECK (array_position(events, NULL) IS NULL),
I'm guessing events is not an enum here since we're enforcing it from the application and that the current set of events are dynamic?

2025-05-01 06:40 UTC, Datron commented on crates/superposition/src/webhooks/helper.rs
> +}
This is why we moved out of file based webhooks.

2025-05-02 04:30 UTC, mahatoankitkumar commented on crates/superposition/src/webhooks/helper.rs
> +}
But, Currently we don't support multiple webhooks for a event, so this check.
Can be removed afterwards, as just a application level check.
I guess this was discussed.

2025-05-02 04:31 UTC, mahatoankitkumar commented on docker-compose/postgres/db_init.sql
> +    events varchar(100)[] NOT NULL CHECK (array_position(events, NULL) IS NULL),
Yup

2025-05-02 04:31 UTC, merged