feat: Support relative path for frontend
juspay/superposition pull request #91
Opened 2024-06-06 12:19 UTC by ayushjain17

Support relative path for frontend

2024-06-07 06:00 UTC, Datron requested changes
A better description for the PR is needed to understand this change

2024-06-07 06:00 UTC, Datron commented on crates/frontend/src/utils.rs
> +    match host.as_str() {
This can be done inside match js_sys::eval() block, if not can we use if condition instead of match?

2024-06-07 06:00 UTC, Datron commented on crates/frontend/src/utils.rs
> +    match host.as_str() {
You can also avoid mutating host variable

2024-06-07 08:17 UTC, pratikmishra356 approved these changes

2024-06-10 07:22 UTC, Datron approved these changes

2024-06-10 09:03 UTC, Datron approved these changes

2024-06-10 16:20 UTC, ShubhranshuSanjeev approved these changes

2024-06-11 05:54 UTC, merged